FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends transmission-daemon=3.00-2.1+deb12u1 && rm -rf /var/lib/apt/lists/*
COPY docker/settings.json /config/settings.json
ENTRYPOINT ["transmission-daemon", "--foreground", "--config-dir", "/config"]
